Capitainisation du document : stoa0040.stoa002
Chartes-TNAH/patrologia_latina-dev pull request #27
Opened 2019-02-18 16:39 UTC by Segolene-Albouy

En réponse à l'issue #5, voici une proposition de capitainisation du [document stoa0040.stoa002](https://github.com/Chartes-TNAH/patrologia_latina-dev/blob/master/data/stoa0040/stoa002/stoa0040.stoa002.opp-lat1.xml). Plusieurs modifications ont été effectuées :
- Découpage du texte en chapitres citables selon le standard CapiTainS
- Déclaration de ce pattern dans le `<cRefPattern>`
- Correction de quelques erreurs d'OCR et des hyphénisations
- Déclaration des modifications appliquées au document dans le `<revisionDesc>`

2019-02-20 15:47 UTC, Marine-F requested changes
Bonjour,
J'ai remarqué une erreur dans le test Travis : vous devriez ajouter l'attribut xml:lang pour spécifier la langue du texte capitainisé pour être totalement valide.

Je pense aussi  que vous pourriez modifier certains éléments : 
- faire quelques corrections supplémentaires de l'OCR, en particulier dans les footnote ;
- pourquoi ne pas ajouter un découpage supplémentaire pour pouvoir citer les paragraphes numérotés ?

2019-02-20 18:41 UTC, Segolene-Albouy commented
Conformément aux remarques de @Marine-F , j'ai renseigné l'attribut `xml:lang` dans la `div` contenant le texte édité ainsi que repris intégralement les erreurs d'OCR à l'intérieur des balises `footnote`.

2019-02-27 08:52 UTC, Marine-F approved these changes

2019-02-27 08:55 UTC, Marine-F commented
Les changements effectués ont été acceptés, je ne vois rien de plus à modifier.
Le test Travis a été passé avec succès.
Cette pull request est prête à être accepter.

2019-03-12 08:37 UTC, merged