Structuration du texte selon les recommandations CapiTains (stoa0040.stoa013h)
Chartes-TNAH/patrologia_latina-dev pull request #30
Opened 2019-02-18 18:10 UTC by Lwizzzzzz

Le texte a été structuré selon les recommandations CapiTains.
Une balise <change> a été ajoutée dans un <revisionDesc> afin de garder une trace des modifications du fichier xml.
(Se référer à l'issue #26 )

2019-02-18 18:48 UTC, cabesse submitted a review, later dismissed
La structure capitains me semble effectivement être correcte, bien que le document numérisé soit lacunaire et prête à confusion. Je me demande toutefois s'il ne manque pas une `div` de niveau chapitre ou sermon pour le début du texte ?

2019-02-18 22:27 UTC, Lwizzzzzz commented
Suite à une deuxième relecture, des corrections ont été ajoutées à la structuration du fichier : de nouveaux chapitres ont été ajoutés.

2019-02-18 22:58 UTC, cabesse requested changes
Après une relecture, je pense que certaines erreurs d'OCR pourraient encore être corrigées. Les changements de chapitre effectués me semblent effectivement appropriés.

2019-02-19 00:06 UTC, Lwizzzzzz commented
Suite aux suggestions soumises, diverses corrections ont été apportées à l'OCR, notamment en ce qui concerne les notes de bas de page.

2019-02-19 11:50 UTC, cabesse approved these changes

2019-02-19 11:50 UTC, cabesse commented
Merci pour les modifications !

2019-02-19 12:28 UTC, cabesse requested changes
Après avoir appris que la validation n'était pas fiable en vérité. J'ai pu voir qu'il te manquait une balise xml:lang dans ta première div. Cf. l'exemple ci-après. Peux-tu la rajouter ? 
`<div type="edition" n="urn:cts:latinLit:stoa0040.stoa013g.opp-lat1" xml:lang="lat">`

2019-02-19 16:44 UTC, Lwizzzzzz commented
@cabesse Merci pour cette remarque très judicieuse ! L'attribut @xml:lang a été rajouté dans la 'div' de premier niveau conformément à l'exemple donné.

2019-02-20 15:03 UTC, cabesse approved these changes

2019-02-20 16:36 UTC, cabesse requested changes
Après avoir demandé quelques précisions à @PonteIneptique, il s'avère qu'il existe un autre document numérisé de cette partie qui vient chambouler l'ordre des div déjà établi (en suivant le premier document numérisé qui était lacunaire et prétait à confusion). Est-ce du coup possible de reprendre la structure capitains, en suivant l'ordre de ce nouveau document ? Pour aide: un -deux sermons globaux / des chapitres / des sous-chapitres ?(correspond aux numéros disséminés dans les paragraphes, cette division est plutôt à considérer comme optionnelle, mais pourra facilement être modifiée le cas échéant.) cf : [document](http://www.documentacatholicaomnia.eu/02m/0354-0430,_Augustinus,_Sermones_Ad_Populum._Sermonum_Quorundam_Ex_Fragmentis,_MLT.pdf)
Il y a également un petit souci au niveau de la fermeture d'une `div` dans la version actuelle (mais sans doute que cela va être corrigé avec les modifications mentionnées ci-dessus). N'hésites pas à utiliser le [vérificateur](https://capitains-validator.herokuapp.com) en ligne pour ton texte.

2019-02-23 09:40 UTC, Lwizzzzzz commented
Suite aux remarques de @cabesse, des corrections ont été apportées concernant la structuration du fichier. A noter que le vérificateur en ligne signale des erreurs concernant les attributs '@urn' et '@xml:lang' alors même que ceux-ci semblent suivre les recommandations des guidelines Capitains. Après quelques recherches, j'ai conclu à un défaut de la part du validateur, mais il est très possible que l'erreur vienne de mon fichier, bien que je ne parvienne pas à en trouver l'origine !

2019-02-23 17:05 UTC, cabesse commented
En fait le problème est au niveau de la fermeture des `div`. Il y a deux petites erreurs qui une fois corrigées de mon côté font que le texte passe les tests. Je pense que comme on était parties sur une idée fausse du texte, ce sont de petits héritages de la première version.

1. La `/div`qui ferme ton premier sermon devrait être placée avant le début du sermon 2 (de manière à créer une subdivision sermon pour tous les premiers chapitres), pour le moment elle est tout à la fin du texte. Il y a donc une `/div`manquante avant le début du sermon 2 et une `/div` en trop à la fin de ton texte.
2. La `/div` de fin de ton sermon 8 (qui contient également des chapitres) est fermées avant les chapitres 5 et 6 alors qu'elle devrait être fermée à la fin du chapitre 6, avant le début du sermon 9. Il y a donc une `/div` en trop à la fin du chapitre 4 et une `/div` manquante après le chapitre 6.

La première capture d'écran montre le résultat du test actuel : 
<img width="635" alt="capture d ecran 2019-02-23 a 17 57 19" src="https://user-images.githubusercontent.com/44814764/53289288-85bdb280-3794-11e9-8b18-0538122afc0d.png">

La deuxième montre ce que tu devrait pouvoir obtenir si tu fais ces changements (en tout cas ce que j'obtiens de mon côté : 
<img width="654" alt="capture d ecran 2019-02-23 a 17 59 19" src="https://user-images.githubusercontent.com/44814764/53289308-c6b5c700-3794-11e9-950f-6fc588292f38.png">

Il me reste toujours une dernière question d'interprétation de la structure du texte en elle-même. Mais là c'est tellement sujet à interprétation que je ne peux considérer comme étant fausse ton idée. J'aurai bien vu un degré d'édition supérieur à ce que tu as identifié comme étant des sermons. Soit un Sermon (avec majuscule faut de meilleure dénomination?) qui inclurait le titre donné à tous ces petits sermons (la première balise `head` du texte.) Ce serait une `div` en plus à placer après la `div `de type edition et qui regrouperait donc tout le texte et tous les sermons avec leurs chapitres... Mais cela revient à avoir trois niveaux de structure (et donc de changer tes déclarations d'en-tête) et honnêtement je ne suis pas sûre de ce qui est attendu de ce côté-là, donc je ne m'offusquerai pas si tu choisis de ne pas l'inclure.

2019-02-23 17:08 UTC, cabesse requested changes
En fait le problème est au niveau de la fermeture des `div`. Il y a deux petites erreurs qui une fois corrigées de mon côté font que le texte passe les tests. Je pense que comme on était parties sur une idée fausse du texte, ce sont de petits héritages de la première version.

    1. La `/div`qui ferme ton premier sermon devrait être placée avant le début du sermon 2 (de manière à créer une subdivision sermon pour tous les premiers chapitres), pour le moment elle est tout à la fin du texte. Il y a donc une `/div`manquante avant le début du sermon 2 et une `/div` en trop à la fin de ton texte.

    2. La `/div` de fin de ton sermon 8 (qui contient également des chapitres) est fermées avant les chapitres 5 et 6 alors qu'elle devrait être fermée à la fin du chapitre 6, avant le début du sermon 9. Il y a donc une `/div` en trop à la fin du chapitre 4 et une `/div` manquante après le chapitre 6.


La première capture d'écran montre le résultat du test actuel :
<img alt="capture d ecran 2019-02-23 a 17 57 19" width="635" src="https://user-images.githubusercontent.com/44814764/53289288-85bdb280-3794-11e9-8b18-0538122afc0d.png">

La deuxième montre ce que tu devrait pouvoir obtenir si tu fais ces changements (en tout cas ce que j'obtiens de mon côté :
<img alt="capture d ecran 2019-02-23 a 17 59 19" width="654" src="https://user-images.githubusercontent.com/44814764/53289308-c6b5c700-3794-11e9-950f-6fc588292f38.png">

Il me reste toujours une dernière question d'interprétation de la structure du texte en elle-même. Mais là c'est tellement sujet à interprétation que je ne peux considérer comme étant fausse ton idée. J'aurai bien vu un degré d'édition supérieur à ce que tu as identifié comme étant des sermons. Soit un Sermon (avec majuscule faut de meilleure dénomination?) qui inclurait le titre donné à tous ces petits sermons (la première balise `head` du texte.) Ce serait une `div` en plus à placer après la `div `de type edition et qui regrouperait donc tout le texte et tous les sermons avec leurs chapitres... Mais cela revient à avoir trois niveaux de structure (et donc de changer tes déclarations d'en-tête) et honnêtement je ne suis pas sûre de ce qui est attendu de ce côté-là, donc je ne m'offusquerai pas si tu choisis de ne pas l'inclure.

2019-02-23 17:53 UTC, Lwizzzzzz commented
@cabesse Merci pour tes explications très détaillées, qui m'ont permis de corriger ces erreurs de structuration. J'ai suivi tes conseils, et ajouté un niveau de structuration suplémentaire, que j'ai choisi de nommer "collection". Après vérification avec le validateur, le texte est maintenant conforme aux recommandations CapiTainS !
![testcapitainsguideline](https://user-images.githubusercontent.com/45824260/53289873-485d2300-379c-11e9-99cc-8f5c66afae2b.png)

2019-02-23 18:19 UTC, cabesse requested changes
Alors là c'est presque parfait ! Et du coup tu as fait le plus difficile reste une petite erreur pour les chemins  : 

Ne penses-tu pas que la valeur de ton MatchPattern devrait être un peu ajustée (le sens et les données sont juste, slt la valeur qui décrit le chemin)?

1. Chapitre (/w+).(/w+).(/w+)
2. Sermon (/w+).(/w+)
3. Collection  (/w+)



<img width="893" alt="capture d ecran 2019-02-23 a 19 14 59" src="https://user-images.githubusercontent.com/44814764/53290071-6c6e3380-379f-11e9-962e-0bcc780aaf65.png">

2019-02-24 15:53 UTC, Lwizzzzzz commented
@cabesse En effet, merci beaucoup d'avoir repéré cette erreur ! Elle a été corrigée conformément à tes indications.

2019-02-25 09:10 UTC, cabesse approved these changes

2019-02-25 09:11 UTC, cabesse commented
Bravo ! Je valide ainsi de mon côté et @PonteIneptique vous pouvez effectuer la validation finale.

2019-03-12 08:54 UTC, merged