Devoir git cf
Chartes-TNAH/patrologia_latina-dev pull request #31
Opened 2019-02-18 18:15 UTC by Corentinfaye

J'ai mis en place la capitaision du texte mais aussi j'ai corriger les hyphetisations comme précisé dans l'issue #19

2019-02-19 09:37 UTC, CamilleCarette approved these changes
Bonjour,

Après lecture du fichier modifié, j'approuve les changements qui y ont été opérés. Merci !

2019-02-19 10:13 UTC, CamilleCarette requested changes
Bonjour,

En y regardant de plus à l'aide du [CapiTainS Validator](https://capitains-validator.herokuapp.com/), l'erreur suivante apparaît : 

Duplicate passages Failed
>>>>>> Duplicate references found : 7

Peut-elle être corrigée ? Merci !

2019-02-25 16:20 UTC, Corentinfaye commented
Je prends note et je corrige l'erreur. J'en profite aussi pour corriger les æ et œ et les remplacer par des ae et oe et ainsi rendre le texte plus lisible.

2019-02-26 10:53 UTC, CamilleCarette commented
Bonjour,

Merci pour ces changements ! Le fichier est valide selon le CapiTainS validator. Je valide donc les changements opérés dans cette pull request.

2019-02-26 10:54 UTC, CamilleCarette approved these changes
Changements approuvés.

2019-03-12 08:59 UTC, merged