Branch dev1
Chartes-TNAH/patrologia_latina-dev pull request #49
Opened 2019-02-19 10:48 UTC by helenedartoisTNAH-M2

Voici la pull request pour les hyphenisations, les ae, la structure d'après les guidelines CapiTainS et le revisionDesc.

2019-02-19 12:18 UTC, olivierjacquot requested changes
Attention, dans une div, un attribut comporte une coquille (paragrpah). Les ae en majuscules sont restées (Æ). Les CAPUT ont bien été supprimés mais le tiret séparant le n° et le début du texte a été gardé avec ou sans des espaces (—). L'OCR ne semble pas avoir été touché (ticndo id te rcvocat)

2019-02-19 13:37 UTC, helenedartoisTNAH-M2 commented
Normalement j'ai fait toutes les corrections, j'espère que cela sera bon!  
Je n'ai pas du tout repris l'OCR, pour le moment.

2019-02-19 15:53 UTC, olivierjacquot submitted a review, later dismissed
Les modifications suggérées ont été apportées. Sauf erreur de ma part, les demandes requises ont été honorées.

2019-02-19 15:56 UTC, olivierjacquot commented
Travis indique 27 erreurs mais le détail ne semble pas accessible (fichier tronqué après la mention : "The job exceeded the maximum time limit for jobs, and has been terminated.")

2019-02-25 08:46 UTC, PonteIneptique commented
Je viens de redémarrer le test sur Travis. Il peut s'agir d'un problème de surcharge serveur.

2019-03-12 09:00 UTC, PonteIneptique commented
@olivierjacquot @helenedartoisTNAH-M2 Je me permets de noter que Travis a bien redémarré et que les résultats sont disponibles.

2019-03-25 08:41 UTC, olivierjacquot approved these changes
Le dernier push corrige la dernière erreur qui subsistait dans le fichier lors du test Epidoc/Single File Validator de Capitains

2019-04-02 14:53 UTC, merged