#5(stoa0040.stoa013g)Exemple de structure du document selon les guidelines CapiTainS
Chartes-TNAH/patrologia_latina-dev pull request #6
Opened 2019-02-14 15:43 UTC by cabesse

Pour faire suite à mon issue #5 : voici un exemple d'un document après capitainisation. Vous remarquerez l'ajout de quelques balises dans le teiHeader et de <div> structurantes dans le contenu.

J'ai également corrigé quelques erreurs d'OCR (quelques problèmes au niveau des ae et des <lb/> et erreurs d'orthographes).

2019-02-17 15:36 UTC, lairaines commented
L'OCR gagnerait à être relue une nouvelle fois, spécialement pour le chapitre 1.

2019-02-17 15:43 UTC, lairaines requested changes
La mise en forme selon les règles Capitains est tout à fait satisfaisante.
Il serait bon de reprendre encore un peu l'OCR, surtout en ce que concerne les AE majuscules et certains espaces en trop pourraient être encore supprimés.

2019-02-18 12:38 UTC, cabesse commented
@lairaines, J'ai pu effectuer les modifications demandées, j'espère qu'elles conviennent.

2019-02-19 11:48 UTC, lairaines submitted a review, later dismissed

2019-02-19 11:49 UTC, lairaines commented
Elles conviennent tout à fait.

2019-02-20 16:30 UTC, lairaines commented
Une remarque sur la structure : ne faudrait-il pas considérer les sermons comme des ensembles de chapitres plutôt que comme des sous chapitres (ce qui laisse supposer la disposition et les attributs actuels des balises ?)

2019-02-21 08:57 UTC, cabesse commented
Effectivement après avoir moi-même été _reviewer_ je me suis rendue compte que ce que j'avais préalablement identifié comme des sermons correspondait en réalité à des subdivisions des chapitres et que le sermon englobait l'ensemble de mon passage. J'ai donc modifié mes 'sermons' en 'schapitre' créant une troisième subdivision qui pourra être facilement supprimée s'il est jugé non nécessaire de la conserver. Comme le travail était déjà fait à ce niveau-là, je me suis dit qu'il était ok de le conserver même si ce n'est que temporaire. @lairaines tu peux effectuer volontiers une dernière vérification avant de valider ces changements.

2019-02-22 14:07 UTC, lairaines commented
Après relecture, le texte retravaillé par @cabesse me parait prêt à être mergé @PonteIneptique.

2019-02-22 14:08 UTC, lairaines approved these changes

2019-02-25 08:42 UTC, merged