(sta0040.stoa014b) Résolution de l'issue #67
Chartes-TNAH/patrologia_latina-dev pull request #68
Opened 2019-02-23 10:19 UTC by FloChiff

Le fichier XML sta0040.stoa014b a été mis aux normes de CapiTains et les informations nécessaires pour le teiHeader ont été ajoutés.

2019-02-23 12:59 UTC, helenedartoisTNAH-M2 commented
Pour le revisionDesc, je pense qu'il faudra ajouter les différentes dates auxquelles tu auras procédé à des ajouts et des modifications sur le document.

2019-02-23 13:11 UTC, MaxDartois reviewed
#68 Ligne 1114-1115 il y a une `<div>` vide.

2019-02-23 13:11 UTC, helenedartoisTNAH-M2 commented on data/stoa0040/stoa014b/stoa0040.stoa014b.opp-lat1.xml
> -						rend="italic">non claudentur.</hi> Quomodo
Ligne 1114-1115, tu as une <div> vide.

2019-02-24 10:12 UTC, FloChiff commented
Résolution de l'issue #70 avec le changement dans les hyphénisations et les æ

2019-02-24 10:43 UTC, helenedartoisTNAH-M2 commented
Tu as tout régularisé par un remplacement ae en minuscule mais dans les titres de chapitres, il faudrait remplacer par AE. Il n'y a que quelques occurrences à remplacer.

2019-02-27 17:21 UTC, MaxDartois reviewed
C'est parfait de mon côté

2019-03-10 21:04 UTC, FloChiff commented
Résolution de l'issue #86 sur les erreurs d'OCR

2019-03-10 21:07 UTC, FloChiff commented
Ajout des changements dans le revisionDesc

2019-03-11 16:36 UTC, MaxDartois submitted a review, later dismissed
Tu as fait un travail de foumis! Bravo!

2019-03-12 17:20 UTC, MaxDartois reviewed
Bonjour, es-tu sûre de ton indentation pour teiHeader et filedesc?
J'ai l'impression qu'il y a trop d'espaces....

2019-03-17 10:24 UTC, MaxDartois requested changes
Deux éléments doivent être modifié dans ce commit: 
1-une hyphénisation est restée inchangée ligne 173,
2-le matchPattern de cRefPattern est identiques pour le chapitre et le paragraphe, cela doit être changé afin d'être conforme aux normes Capitains.

2019-03-17 10:24 UTC, helenedartoisTNAH-M2 commented on data/stoa0040/stoa014b/stoa0040.stoa014b.opp-lat1.xml
> +						<title type="main">ADVERSUS QUINQUE HÆRESES, SEU CONTRA QUINQUE HOSTIUM
Bonjour, 
Une hyphénisation a été oublié ici (ligne 173): HÆRESES -> HAERESES.

2019-03-17 10:24 UTC, helenedartoisTNAH-M2 commented on data/stoa0040/stoa014b/stoa0040.stoa014b.opp-lat1.xml
> +					replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:div[@n='$2'])">
Est-ce normal que ton matchPattern soit le même pour le paragraphe et le chapitre?

2019-03-18 16:57 UTC, helenedartoisTNAH-M2 commented on data/stoa0040/stoa014b/stoa0040.stoa014b.opp-lat1.xml
> +						<title type="main">ADVERSUS QUINQUE HÆRESES, SEU CONTRA QUINQUE HOSTIUM
Tout est résolu de mon côté.

2019-03-18 16:58 UTC, helenedartoisTNAH-M2 commented on data/stoa0040/stoa014b/stoa0040.stoa014b.opp-lat1.xml
> +					replacementPattern="#xpath(/tei:TEI/tei:text/tei:body/tei:div/tei:div[@n='$1']/tei:div[@n='$2'])">
Je n'ai rien dit, j'ai mal lu! Tout est ok!

2019-03-18 16:59 UTC, MaxDartois submitted a review, later dismissed

2019-03-24 12:45 UTC, FloChiff commented
Ajout de multiples modifications pour que le document soit conforme.

2019-03-24 13:00 UTC, MaxDartois approved these changes
Tout semble bon, j'ai passé le document dans Capitains Validator, tous les tests sont bons.

2019-04-02 14:55 UTC, merged