#25 _ Structuration du fichier selon les recommandations de CapiTains
Chartes-TNAH/patrologia_latina-dev pull request #76
Opened 2019-02-26 08:27 UTC by LucetteV

En référence à l'issue #25 correction des "ae/AE" et des espaces entre les <lb/>.

2019-02-27 13:44 UTC, Lwizzzzzz requested changes
@LucetteV Après une première lecture de ton fichier, je pense que tu as correctement ajouté la plupart des éléments qui étaient essentiels pour la Capitainisation de ce texte. La structuration me semble conforme, et elle est correctement référencée dans le teiHeader. De même, tes modifications du fichier TEI on bien été documentées grâce à la balise `change`.

Grâce au [vérificateur](https://capitains-validator.herokuapp.com/) en ligne, j'ai décelé une petite erreur à corriger :
![lucie_test](https://user-images.githubusercontent.com/45824260/53493035-acccfa80-3a9a-11e9-940a-3bda547fd8ad.png)
Comme tu peux le voir, l'erreur vient de la première `div`, à laquelle il faudrait que tu ajoutes un attribut `@xml:lang` de la manière suivante : 
`<div type="edition" n="urn:cts:latinLit:stoa0040.stoa015.opp-lat1" xml:lang="lat">`

En dehors de cette petite correction, j'ai quelques suggestions qui ne sont pas obligatoires, mais qui pourraient être utiles pour la compréhension du code : 

1. D'après la version numérisée, il me paraîtrait judicieux de rajouter un niveau de structuration supplémentaire, une div qui engloberait tes div de niveau "chapter", qui pourrait s'appeler par exemple "collection".
2. Pour faire suite à la correction des "oe", il pourrait être judicieux de faire également les "ae", qui sont soumis au même problème de lisibilité.
3. Enfin, peut-être pourrais-tu ajouter quelques corrections générales à l'OCR, notamment en ce qui concerne les notes de bas de page ?

2019-03-12 12:24 UTC, LucetteV commented
Issue #87 : j'ai procédé aux suggestions xml:lang / @subtype="collection" / Modifications des oe/OE.
 
La correction de l'OCR est prévue.

2019-03-27 12:25 UTC, LucetteV commented
Bonjour suite à #76 
Suite à un problème d'ordinateur, qui est actuellement en pré-réparation (je dois valider ou non le devis d'ici 7 jours, ensuite il pourra être réparé) j'ai tenté de récupérer comme j'ai pu mes données. Ce fut une gymnastique que de me retrouver dans les dossiers sur un autre ordinateur, avec un autre système. Les modifications faites par 'Benjamin GOUT' ont été réalisées en fait par moi. Seulement je n'ai pas accès à mon système OS. 
@Lwizzzzzz je te laisse me dire ce que tu en penses ? J'ai finalisé la correction de l'ocr jusqu'au commentaire au chapitre 13, j'ai également repris les notes de bas de page, et tenté de corriger les passages en "grec".

2019-03-31 11:18 UTC, Lwizzzzzz approved these changes

2019-03-31 11:18 UTC, Lwizzzzzz commented
@LucetteV Après avoir consulté ton fichier, il me semble que tes corrections sont tout à fait conformes à ce qui était attendu. Le vérificateur en ligne ne fonctionnant pas, il est difficile de vérifier avec certitude, mais je pense que ton travail est conforme aux recommandations capitains !
Bon courage avec ton ordinateur :)

2019-04-01 19:08 UTC, LucetteV commented
Push du fichier, en attente de merging.
@Lwizzzzzz merci pour ton retour.

2019-04-02 12:59 UTC, merged