stoa0040.stoa013c) Résolution des issues #21, #82 et #84
Chartes-TNAH/patrologia_latina-dev pull request #85
Opened 2019-03-07 17:45 UTC by Victorialf

Bonjour,
J'ai résolu les issues #21 , #84  , #84 . 
Ainsi j'ai réalisé en plusieurs étapes: 
- le remplacement des ae
- le traitement des hypéhnisations
- la capitainisation du fichier (structuration des chapitres en div, ajout de l'attribut xml:lang, modification de l'encodingDesc et du revisionDesc).
(stoa0040.stoa0113c).

2019-03-08 11:56 UTC, Carolinemeot commented
Bonjour, 
j'ai testé votre code dans le validateur de CapiTainS et tout est correct. Cependant, je pense que vous pourriez éventuellement retirer les intitulés des chapitres et des sermons ("CAPUT PRIMUM", "SERMO CLXXXIV", etc.) car il s'agit maintenant d'une information superflue depuis l'ajout des div.

2019-03-08 11:59 UTC, Carolinemeot requested changes
Bonjour,
j'ai testé votre code dans le validateur de CapiTainS et tout est correct. Cependant, je pense que vous pourriez éventuellement retirer les intitulés des chapitres et des sermons ("CAPUT PRIMUM", "SERMO CLXXXIV", etc.) car il s'agit maintenant d'une information superflue depuis l'ajout des div.

2019-03-27 22:06 UTC, Victorialf commented
Bonjour, 

J'ai apporté les modifications demandées par @Carolinemeot, le fichier est donc capitanisé dans les règles.

2019-03-28 18:08 UTC, Carolinemeot submitted a review, later dismissed

2019-03-28 18:09 UTC, Carolinemeot commented
Merci Victoria pour ce travail, cela correspond tout à fait à ce qui était demandé.

2019-04-02 13:26 UTC, merged